[package]
name = "rustio"
authors = ["Felix Häcker <haecker.felix1207@gmail.com>"]
license = "GPL-3.0"
version = "0.0.1"
description = "Rust API wrapper for radio-browser.info"

[dependencies]
restson = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
