[package]
name = "rustio"
authors = ["Felix Häcker <haecker.felix1207@gmail.com>"]
license = "GPL-3.0"
version = "0.0.1"
description = "Rust API wrapper for radio-browser.info"

[dependencies]
reqwest = "0.8.5"
serde = "1.0.43"
serde_json = "1.0"
serde_derive = "1.0.43"
log = "0.4"
failure = "0.1.1"
glib = "0.5.0"

[dependencies.gtk]
version = "0.4.0"
features = ["v3_22"]